general:
  kafka-topic: trader-updates

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false  # keep false - we don't need headers

    consumer:
      group-id: midas
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.jpmc.midascore.foundation
        spring.json.value.default.type: com.jpmc.midascore.foundation.Transaction   # <--- ADD THIS LINE
    listener:
      ack-mode: MANUAL_IMMEDIATE